### ISSUE TITLE
Bulk importer not apearing in pkhex

### ISSUE THREAD

**Issue by Retroyawn** [CDNRae/pkhex-bulk-egg-generator#16]
I did everything the steps told me to.
I have a plugins folder where pkhex.exe is. I also extracted the bulk importer into that folder but I don't see bulk importer in pkhex  in the tools menu 
I don't know what's wrong,  but i would apreciate any help that can be give

**Comment by CDNRae** [comment]
Try using the updated plugin -- the last release prior to 2.0.0 was about 2yrs out of date, and incompatible with the later versions of PKHeX.
