### ISSUE TITLE
I can not insert generated eggs

### ISSUE THREAD

**Issue by Sycrax** [CDNRae/pkhex-bulk-egg-generator#2]
It fails everytime with the following error:

Exception Details:
System.ArgumentOutOfRangeException: Das angegebene Argument liegt außerhalb des gültigen Wertebereichs.
Parametername: game
   bei PKHeX.Core.GameData.Personal(GameVersion game)
   bei PKHeX.Core.GameData.GetLearnset(GameVersion game, Int32 species, Int32 form)
   bei PKHeX.Core.EncounterEgg.SetEncounterMoves(PKM pk, GameVersion version)
   bei PKHeX.Core.EncounterEgg.ConvertToPKM(ITrainerInfo sav, EncounterCriteria criteria)
   bei BulkImporter.BulkImporterPlugin.AddToBoxesButtonClick(Object sender, EventArgs events)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll

PKHeX, Version=21.5.21.0, Culture=neutral, PublicKeyToken=null
C:\Users\Sycrax\Desktop\Pokepatch\PKHeX.exe

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll

System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll

System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll

System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

System.Reflection, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Reflection\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Reflection.dll

System.Runtime.InteropServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.InteropServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.InteropServices.dll

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed

System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll

System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll

System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll

System.Windows.Forms.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.Windows.Forms.resources.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

BulkImporter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\Sycrax\Desktop\Pokepatch\plugins\BulkImporter.dll

Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
C:\Users\Sycrax\Desktop\Pokepatch\plugins\Newtonsoft.Json.dll

mscorlib.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by dermosdragon** [comment]
Im having this same problem but mine is just with gen 7

**Comment by CDNRae** [comment]
@Sycrax so sorry for the delay in getting to you.  I'm having a hard time replicating this error.  Can you provide me with the following info?

1. How many Pokemon are you importing?
2. What game are you importing Pokemon to?
3. What version of PKHeX are you using?

**Comment by dermosdragon** [comment]
the problem was 120 eggs 10% on all the other stuff for Ultra moon and I'm
using the latest version of pkhex

I did do this with less pokemon and it worked so they might just be a few
pokemon that cause the problem.

**Comment by CDNRae** [comment]
@dermosdragon I don't know if this is the same issue that @Sycrax is experiencing, but your problem seems to be related to issue #4.  There seems to be a limit to how much text can fit into the text area box in PKHeX; once you go over 100 Pokemon it's hit or miss.  I'm looking into how to fix this.

**Comment by Sycrax** [comment]
> 
> 
> @Sycrax so sorry for the delay in getting to you. I'm having a hard time replicating this error. Can you provide me with the following info?
> 
>     1. How many Pokemon are you importing?
> 
>     2. What game are you importing Pokemon to?
> 
>     3. What version of PKHeX are you using?

Now I am the one who is sorry for the delay xD

1) I tried out 50 and 1, none of them worked.
2) 4780 - Pokemon HeartGold (U)(Xenophobia) _Itried the German Version to, but it didnt work either_
3) PKHeX (20210521)

**Comment by CDNRae** [comment]
Thanks for the info!  I did some testing and it seems like HGSS have some quirks to the way they handle Pokemon data.  I'm working on a fix for this now, hopefully I'll have it up soon for you!

**Comment by Sycrax** [comment]
Could it be that this Problem, is somehow a gen4 problem? I tried to insert eggs on a Platinum save File and it didnt work either.

But hey i am glad you are working on this, actually im pretty thankful. If there is anything i can do to help you let me know!

**Comment by CDNRae** [comment]
Hmmm, I think you've hit the nail on the head there.  There's something unique to the way the data is being handled for Gen 4.

And thank you!  I really appreciate that -- honestly just reporting any and all bugs you find is super helpful, it's just me working on this tool so it takes awhile to test everything.

**Comment by Sycrax** [comment]
I'll do some intense testing once ur done :D 

Now that the gen4 remakes come out this november i have some time i need to waste xD

**Comment by Princessdmg** [comment]
> @Sycrax so sorry for the delay in getting to you. I'm having a hard time replicating this error. Can you provide me with the following info?
> 
> 1. How many Pokemon are you importing?
> 2. What game are you importing Pokemon to?
> 3. What version of PKHeX are you using?

I am having the same problem 
1. 30 pokemon
2. pokemon sun
3. pkhex(20220318)

**Comment by Sycrax** [comment]
@CDNRae did you find anything? I really would love to play a Pokemon Egglocke of Pokemon Platinum on my stream.

**Comment by CDNRae** [comment]
Should be fixed in version 2.0.0.
