### ISSUE TITLE
Can't import eggs

### ISSUE THREAD

**Issue by Kecleon05** [CDNRae/pkhex-bulk-egg-generator#4]
PKHeX launches fine but when I attempt to import the eggs I get the following error.
Exception Details:
Newtonsoft.Json.JsonReaderException: Invalid character after parsing property name. Expected ':' but got: 

any chance there is a way to fix this. I love the concept of the tool and have been searching for something like it.

**Comment by Kecleon05** [comment]
Don't know if this was actually the solution but it worked when I imported less eggs but also the second time I had mons in the boxes and it gave them the eggs as held items but didn't work when I had empty boxes.

**Comment by CDNRae** [comment]
I'm guessing that there's a value in the generated eggs that PKHeX doesn't like -- I've seen it crop up a few times with move names (i.e. "StringShot" vs "String Shot").  Importing in smaller amounts will help circumvent this.  You shouldn't see a difference when the boxes are empty vs. when they have Pokemon in them.  Can you clarify what you mean when you say that it gave Pokemon the eggs as held items?

**Comment by Kecleon05** [comment]
Sorry just checked and this was caused by my lack of understanding of the PKHeX interface and my overstuffed boxes. When the mons are eggs it shows an egg where the held item normally is, that is my mistake. As for the numbers It failed when on 150 but 30 at a time seemed to work.

**Comment by CDNRae** [comment]
I ran a few tests and it looks like there's a character limit on the text area in PKHeX -- once I went over 100 Pokemon generated it was hit or miss as to whether or not all that info could fit in the text box.  I'll see if I can fix that, and if not, I guess I'll have to implement a limit on the website.  Thanks for bringing this to my attention!

**Comment by CDNRae** [comment]
Should be fixed in version 2.0.0.
