### ISSUE TITLE
Importing eggs doesn't seem to be compatible with the latest version of pkhex

### ISSUE THREAD

**Issue by SmileycorpMC** [CDNRae/pkhex-bulk-egg-generator#7]
I generated an egg using the generator, then tried importing it with the latest version and got this error:

https://pastebin.com/Nsj2Wdct

I'm importing into a blank omega ruby save, in case that matters.

**Comment by devn456** [comment]
I also got this problem and im using a Pokemon black save

**Comment by CDNRae** [comment]
Should be fixed in version 2.0.0.
